### ISSUE TITLE
Problem with “In Memory Panic Stackshot Succeeded”

### ISSUE THREAD

**Issue by wu5789** [evandavid/opencore-b460m-itx-i9-10900-rx6600#1]
Hello ,I have exactly the same model as you .Everything works fine in Catalina. After I successfully installed Big Sur ,it failed to boot in the system ,getting stuck at “In Memory Panic Stackshot Succeeded”.

I'm wondering if you have any idea? 

Thanks!

**Comment by evandavid** [comment]
Hi
i think some of kext here is not updated
maybe try to update to latest version first?

i got big sur installed from 'software update' and not having issue at all

**Comment by wu5789** [comment]
Ok,I'll try it out later.Thanks for your reply.

I've also learned that the problem might occur owing to the allocated ram of iGPU.However,10400f doesn't have iGPU within it,which makes it utterly impossible to allocate the ram or even disable the iGPU from bios.

**Comment by wu5789** [comment]
Never mind the ram problem as I have mentioned above.

I made a new EFI folder by upgrading the kexts.Now I am able to boot successfully.The kexts really seems to be the problem that you are talking about.

Anyway,you have helped me a lot .Thanks!![Uploading 100250927...]
