### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by Zhouguangwei327** [evandavid/opencore-b460m-itx-i9-10900-rx6600#4]
i use this EFI to install macos, but reboot the mechine, the comouter screen is black, how to solve it?

**Comment by evandavid** [comment]
do you have the same hardware as mine?

**Comment by NFhook** [comment]
Login blank screen
Hardware：「  i9 10850K + Asus TUF Gaming B460M-Plus + RX6600XT  」
