### ISSUE TITLE
about BCM943224PCIEBT2

### ISSUE THREAD

**Issue by hdchieh** [evandavid/opencore-b460m-itx-i9-10900-rx6600#5]
I also use bcm943224pciebt2.
With AirportBrcmFixup & BlueToolFixup,
![](https://user-images.githubusercontent.com/33096672/211604597-85b58291-405d-4b63-b486-a379158aa99d.png)
Currently, airdrop, wifi, and Bluetooth are all working, but you can't use iPhone as a camera or a microphone. I'm not sure what the problem is.
![](https://user-images.githubusercontent.com/33096672/211605337-c5b0faf5-d142-4726-93f9-25d765664d6f.png)

**Comment by hdchieh** [comment]
![Screenshot 2023-01-15 at 02 37 37](https://user-images.githubusercontent.com/33096672/212490605-4e9eff3f-50b9-46db-b794-6dd7b497bf13.png)
I have tried to add these five .kext, but the problem remains.
Hopefully, you could give me some advice. Thanks.

**Comment by evandavid** [comment]
Hi @hdchieh 

I don't have the same issue, I can connect both the microphone and camera
<img width="266" alt="Screenshot 2023-01-20 at 09 42 45" src="https://user-images.githubusercontent.com/1207161/213606952-b73e5a6f-b77c-4d24-9918-b3a74b3014b2.png">

I use the same apple ID on both devices

**Comment by evandavid** [comment]
and I forgot to mention, that I use the same apple ID on both device
