### ISSUE TITLE
is rx6600 works with catalina ?

### ISSUE THREAD

**Issue by jhonoryza** [evandavid/opencore-b460m-itx-i9-10900-rx6600#6]
i see dortania docs only works for monterey

**Comment by evandavid** [comment]
I don't have the answer for that, because I use Sapphire Pulse RX 6600 with Ventura
previously I use RX570 and work with Catalina

(kenapa ga di update aja ke Ventura om?)

**Comment by jhonoryza** [comment]
kebetulan os nya masi catalina dan gpu nya pake GT710, sekarang gpu nya upgrade ke RX6600
